### ISSUE TITLE
Question about '?'

### ISSUE THREAD

**Issue by kuator** [henricattoire/aergia#1]
Would be kind to explaind what exactly question mark does in this line of code?
`globpath(g:aergia_snippets, '**/' . &filetype . '?' . l:key)`
I read the help page that question mark is used for optional characters in regex. But here it expands to find a snippet file. And I don't understand why?

**Comment by kuator** [comment]
Okay, I accidentally stumbled on help page on wildcards, and funny enough, straight away it says what ? does.

**Comment by henricattoire** [comment]
Thanks for bringing this to my attention. I changed `aergia` to only accept a `_` or `-` between the filetype and the name of the snippet. This makes `aergia` a bit more predictable when it looks for filetype specific snippets. The ? actually just represents 0 or 1 character(s).
