### ISSUE TITLE
Error detected while processing .../syntax/aergia.vim

### ISSUE THREAD

**Issue by averms** [henricattoire/aergia#17]
I get this when trying to open a snippet file. Here is the full error

```
E121: Undefined variable: g:aergia_tag
E116: Invalid arguments for function get
E15: Invalid expression: '"' . get(g:aergia_tag, 'open') . '.\{-1,}' . get(g:aergia_tag, 'close') .
'"'
```

**Comment by averms** [comment]
I think this happens because syntax files are loaded before plugin files. See `:h startup`.

**Comment by henricattoire** [comment]
You are probably right but I can't seem to reproduce the bug. If I open a snippet file, `ftdetect` silently fails and thus the syntax file never runs as it doesn't recognise the file to be a snippet. I never came across this bug in the first place as I only use commands (`:h aergia-commands`) to interact with snippets. Any suggestions on a fix?

**Comment by henricattoire** [comment]
I decided to work around this problem and introduce the `.ae` extension for aergia snippets. I also removed the ability to change the tag delimiters as I now think this of this as an unnecessary level of costumisation. You can find everything on the `next` branch. Let me know what you think?
