### ISSUE TITLE
Respect buffer indent settings

### ISSUE THREAD

**Issue by ghost** [henricattoire/aergia#3]
I write my snippets using tabs so that they don't care in what kind of buffer they are pasted.
```
def <{name}>():
	""": <{+}> """
	<{name}>
	<{+}>
```

However if I edit a javascript file where my settings are `set shiftwidth=2 tabstop=2 expandtab`. Then the snippet above will still indent with tabs.

Expected:
Settings are respected and snippet would indent with 2 spaces instead.

**Comment by henricattoire** [comment]
Closing issue for now as it should be fixed. Note for people who use vim's packaging system to load plugins: put `filetype indent plugin on` after all your `packadd ` statements, otherwise ftdetect directories will not be considered.

**Comment by henricattoire** [comment]
One [snippet](https://github.com/henricattoire/aergia/blob/master/snippets/python/python_deff) still doesn't  have the correct indentation when using it. Reopening for now.

**Comment by henricattoire** [comment]
Indentation is fixed now, closing.
