### ISSUE TITLE
Commands' completion list snippets twice

### ISSUE THREAD

**Issue by Jorenar** [henricattoire/aergia#6]
Both `:AergiaEditSnippet` and `:AergiaRemoveSnippet` lists snippets two times.

For example, `::AergiaEditSnippet <Tab>` will give:

    c_def  c_def  c_for  c_for  cpp_cl  cpp_cl

in wildmenu, even though there is only one file of each name.

**Comment by henricattoire** [comment]
I didn't know about that bug, thanks, I'll quickly test your pull request (although it's straightforward) and merge it into master.
